export { default as Home } from "./Home";
export { default as Links } from "./Links";
export { default as Bio } from "./Bio";
export { default as Gallery } from "./Gallery";
export { default as Form } from "./Form";
export { default as Blog } from "./Blog";
export { default as Signin } from "./Signin";
export { default as Register } from "./Register";
export { default as User } from "./User";
